name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Fetch and pull from remote
        run: |
          git fetch origin main
          git pull origin main --rebase

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://lalumahato:$HF_TOKEN@huggingface.co/spaces/lalumahato/Search_Engine main
